#!/bin/bash
# Creates one database per service, each with its own least-privilege roles, since the official postgres
# image only creates the single database named by POSTGRES_DB. Reads a comma-separated list of
# "<service>_db" names from POSTGRES_MULTIPLE_DATABASES and, for each <service>:
#
#   <service>_owner  LOGIN   owns the database; runs Flyway migrations (and, without Vault, the app).
#                            Password comes from <SERVICE>_DB_PASSWORD - generated by scripts/gen-env.sh.
#   <service>_app    NOLOGIN group role holding only DML rights on whatever the owner creates. When
#                            Vault is enabled it mints short-lived login roles that are members of it
#                            (see infrastructure/vault/), so the running service never holds DDL rights.
#
# vault_admin (only when VAULT_DB_ADMIN_PASSWORD is set) is the login HashiCorp Vault uses to mint
# short-lived <service>_app members; it holds CREATEROLE and ADMIN OPTION on those group roles only.
#
# No role can reach another service's database: CONNECT is revoked from PUBLIC.
set -euo pipefail

if [ -z "${POSTGRES_MULTIPLE_DATABASES:-}" ]; then
    exit 0
fi

echo "Creating databases: $POSTGRES_MULTIPLE_DATABASES"
IFS=',' read -ra DATABASES <<< "$POSTGRES_MULTIPLE_DATABASES"

for db in "${DATABASES[@]}"; do
    db="$(echo "$db" | xargs)"
    svc="${db%_db}"
    owner="${svc}_owner"
    app="${svc}_app"
    pw_var="$(echo "$svc" | tr '[:lower:]' '[:upper:]')_DB_PASSWORD"
    pw="${!pw_var:?$pw_var must be set (run scripts/gen-env.sh)}"

    echo "Provisioning $db: roles $owner / $app"

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-EOSQL
        DO \$\$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${owner}') THEN
                CREATE ROLE ${owner} LOGIN PASSWORD '${pw}';
            ELSE
                ALTER ROLE ${owner} PASSWORD '${pw}';
            END IF;
            IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${app}') THEN
                CREATE ROLE ${app} NOLOGIN;
            END IF;
        END
        \$\$;

        SELECT 'CREATE DATABASE ${db} OWNER ${owner}'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${db}')\gexec

        REVOKE ALL ON DATABASE ${db} FROM PUBLIC;
        GRANT CONNECT ON DATABASE ${db} TO ${app};
EOSQL

    if [ -n "${VAULT_DB_ADMIN_PASSWORD:-}" ]; then
        # Vault's own login: may create/drop roles and place them in <service>_app, nothing else.
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-EOSQL
            DO \$\$
            BEGIN
                IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'vault_admin') THEN
                    CREATE ROLE vault_admin LOGIN CREATEROLE PASSWORD '${VAULT_DB_ADMIN_PASSWORD}';
                ELSE
                    ALTER ROLE vault_admin PASSWORD '${VAULT_DB_ADMIN_PASSWORD}';
                END IF;
            END
            \$\$;
            GRANT CONNECT ON DATABASE ${db} TO vault_admin;
            GRANT ${app} TO vault_admin WITH ADMIN OPTION;
EOSQL
    fi

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$db" <<-EOSQL
        GRANT USAGE ON SCHEMA public TO ${app};
        -- Anything the owner creates later (Flyway migrations) becomes usable by the app role, DML only.
        ALTER DEFAULT PRIVILEGES FOR ROLE ${owner} IN SCHEMA public
            GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${app};
        ALTER DEFAULT PRIVILEGES FOR ROLE ${owner} IN SCHEMA public
            GRANT USAGE, SELECT ON SEQUENCES TO ${app};
EOSQL
done
