apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  db-username: {{ .Values.secrets.dbUsername | quote }}
  db-password: {{ .Values.secrets.dbPassword | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
