#!/bin/sh
# Initialises, unseals and configures Vault for the local stack. Runs as the one-shot `vault-init`
# container on every `docker compose up`; safe to re-run.
#
# First run
#   1. initialises Vault (1 key share - local convenience; production uses 5 shares, threshold 3)
#   2. unseals it, enables an audit log, the KV v2 store, the database engine and AppRole auth
#   3. writes one least-privilege policy per service and seeds the secrets from the environment
#   4. creates an AppRole per service and drops its role-id / secret-id into /bootstrap/approle/<service>/
#   5. issues an operator token with the `admin` policy and REVOKES the root token
# Every later run
#   - unseals Vault if it restarted, and (re)applies the database configuration if Postgres is up
#
# The unseal key and operator token live in /bootstrap (the host's git-ignored ./.vault/). That is a
# deliberate local-development convenience; in a real deployment the unseal key is split between
# operators or delegated to a cloud KMS (auto-unseal).
set -eu

VAULT_ADDR="${VAULT_ADDR:-http://vault:8200}"
export VAULT_ADDR
BOOT=/bootstrap
POLICIES=/policies
mkdir -p "$BOOT"

SERVICES="customer-service order-service inventory-service payment-service notification-service"
DB_SERVICES="customer order inventory payment notification"

log() { echo "[vault-init] $*"; }

status_field() { vault status -format=json 2>/dev/null | sed -n "s/.*\"$1\": *\([a-z]*\).*/\1/p"; }

# --- wait for the API ------------------------------------------------------------------------------
log "waiting for Vault at $VAULT_ADDR"
i=0
until [ "$(vault status >/dev/null 2>&1; echo $?)" != "1" ]; do
  i=$((i + 1)); [ "$i" -gt 60 ] && { log "Vault did not become reachable"; exit 1; }
  sleep 1
done

# --- initialise ------------------------------------------------------------------------------------
if [ "$(status_field initialized)" = "false" ]; then
  log "initialising Vault"
  out="$(vault operator init -key-shares=1 -key-threshold=1 -format=json)"
  printf '%s' "$(echo "$out" | sed -n 's/.*"root_token": *"\([^"]*\)".*/\1/p')" > "$BOOT/root-token"
  printf '%s' "$(echo "$out" | grep -A1 '"unseal_keys_b64"' | tail -n1 | tr -d ' ",')" > "$BOOT/unseal-key"
  chmod 600 "$BOOT/root-token" "$BOOT/unseal-key" 2>/dev/null || true
fi

# --- unseal ----------------------------------------------------------------------------------------
if [ "$(status_field sealed)" = "true" ]; then
  [ -s "$BOOT/unseal-key" ] || { log "Vault is sealed and no unseal key is available in $BOOT"; exit 1; }
  log "unsealing"
  vault operator unseal "$(cat "$BOOT/unseal-key")" >/dev/null
fi

# After an unseal, a Raft node needs a moment to win the leader election; requests before that fail
# with "local node not active". Poll with the token until the API answers.
wait_active() {
  n=0
  until vault token lookup >/dev/null 2>&1; do
    n=$((n + 1)); [ "$n" -gt 60 ] && { log "Vault never became active"; exit 1; }
    sleep 1
  done
}

# --- one-time configuration ------------------------------------------------------------------------
if [ ! -f "$BOOT/configured" ]; then
  export VAULT_TOKEN="$(cat "$BOOT/root-token")"
  wait_active
  log "configuring Vault (first run)"

  vault audit enable file file_path=/vault/logs/audit.log >/dev/null
  vault secrets enable -path=secret -version=2 kv >/dev/null
  vault secrets enable database >/dev/null
  vault auth enable approle >/dev/null

  # Policies: one per service, plus the operator policy.
  vault policy write admin "$POLICIES/admin.hcl" >/dev/null
  vault policy write api-gateway "$POLICIES/gateway.hcl" >/dev/null
  for svc in $SERVICES; do
    sed "s/__SERVICE__/$svc/g" "$POLICIES/service.hcl" | vault policy write "$svc" - >/dev/null
  done

  # Secrets, seeded from the environment compose passes in (generated by scripts/gen-env.sh).
  : "${REDIS_PASSWORD:?}" "${NOTIFICATION_CLIENT_SECRET:?}"
  vault kv put secret/application "spring.data.redis.password=$REDIS_PASSWORD" >/dev/null
  for db in $DB_SERVICES; do
    upper="$(echo "$db" | tr '[:lower:]' '[:upper:]')"
    eval "pw=\${${upper}_DB_PASSWORD:?${upper}_DB_PASSWORD is not set}"
    if [ "$db" = "notification" ]; then
      # Schema-migration login (the database owner) and this service's own client-credentials secret.
      vault kv put "secret/${db}-service" \
        "db.migration.username=${db}_owner" "db.migration.password=$pw" \
        "ecommerce.service-auth.client-secret=$NOTIFICATION_CLIENT_SECRET" >/dev/null
    else
      vault kv put "secret/${db}-service" \
        "db.migration.username=${db}_owner" "db.migration.password=$pw" >/dev/null
    fi
  done

  # AppRole identities: how each service proves who it is to Vault.
  for svc in api-gateway $SERVICES; do
    vault write "auth/approle/role/$svc" token_policies="$svc" token_ttl=1h token_max_ttl=4h \
      secret_id_ttl=0 token_num_uses=0 >/dev/null
    mkdir -p "$BOOT/approle/$svc"
    # File names are the Spring property names, so the service's mounted /run/secrets directory is read
    # as-is by spring.config.import=configtree:/run/secrets/.
    printf '%s' "$(vault read -field=role_id "auth/approle/role/$svc/role-id")"       > "$BOOT/approle/$svc/spring.cloud.vault.app-role.role-id"
    printf '%s' "$(vault write -f -field=secret_id "auth/approle/role/$svc/secret-id")"       > "$BOOT/approle/$svc/spring.cloud.vault.app-role.secret-id"
    chmod 644 "$BOOT"/approle/"$svc"/spring.cloud.vault.app-role.* 2>/dev/null || true
  done

  # Operator token, then retire root.
  # -orphan: revoking the root token below must not revoke this one (child tokens die with their parent).
  vault token create -orphan -policy=admin -period=768h -display-name=operator -field=token > "$BOOT/admin-token"
  chmod 600 "$BOOT/admin-token" 2>/dev/null || true
  vault token revoke -self >/dev/null
  rm -f "$BOOT/root-token"
  touch "$BOOT/configured"
  log "core configuration done; root token revoked, operator token in .vault/admin-token"
fi

# --- database secrets engine (needs Postgres; skipped quietly for the H2 stack) ----------------------
export VAULT_TOKEN="$(cat "$BOOT/admin-token")"
wait_active
if [ -n "${VAULT_DB_ADMIN_PASSWORD:-}" ] && nc -z -w 3 postgres 5432 2>/dev/null; then
  log "configuring dynamic database credentials"
  for db in $DB_SERVICES; do
    vault write "database/config/${db}-service" \
      plugin_name=postgresql-database-plugin \
      allowed_roles="${db}-service" \
      connection_url="postgresql://{{username}}:{{password}}@postgres:5432/${db}_db?sslmode=disable" \
      username=vault_admin password="$VAULT_DB_ADMIN_PASSWORD" >/dev/null
    # Each login role Vault creates is a member of <db>_app: DML on that one database, no DDL.
    vault write "database/roles/${db}-service" \
      db_name="${db}-service" \
      creation_statements="CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}' IN ROLE ${db}_app;" \
      revocation_statements="DROP ROLE IF EXISTS \"{{name}}\";" \
      default_ttl=12h max_ttl=168h >/dev/null
  done
else
  log "Postgres not reachable (or VAULT_DB_ADMIN_PASSWORD unset): skipping database credentials"
fi

log "ready"
