apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  jwt-secret: "mySecretKeyForJWTTokenSigningPurposeOnly12345678901234567890"
  db-username: "sa"
  db-password: "password"
  redis-password: "redisPassword123"
  config-repo-username: "admin"
  config-repo-password: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: ecommerce
type: docker.io/dockercfg
data:
  .dockercfg: eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiYWRtaW4iLCJhdXRoIjoiWVdSdGFXNDZZbUZ6In19
