-- Notification Service - Oracle Database Schema

CREATE TABLE notifications (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER(19) NOT NULL,
    order_id NUMBER(19),
    type VARCHAR2(50) NOT NULL,
    recipient VARCHAR2(255) NOT NULL,
    subject VARCHAR2(255) NOT NULL,
    message VARCHAR2(2000) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    error_message VARCHAR2(500),
    source_event_id VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uk_notifications_source_event_id UNIQUE (source_event_id)
);

CREATE INDEX idx_notifications_customer_id ON notifications (customer_id);
CREATE INDEX idx_notifications_order_id ON notifications (order_id);
CREATE INDEX idx_notifications_type ON notifications (type);
CREATE INDEX idx_notifications_status ON notifications (status);
CREATE INDEX idx_notifications_created_at ON notifications (created_at);
