-- Inventory Service - H2 Sample Data

INSERT INTO inventory (id, product_id, quantity, created_at, updated_at)
VALUES
    (1, 'PROD-001', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'PROD-002', 150, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'PROD-003', 75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 'PROD-004', 200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 'PROD-005', 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (6, 'PROD-006', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (7, 'PROD-007', 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (8, 'PROD-008', 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE
    quantity = VALUES(quantity),
    updated_at = CURRENT_TIMESTAMP;
