#!/bin/bash
# Generates the local secrets file (.env) used by docker compose.
#
# Nothing in this repository carries a usable credential any more: every password, client secret and
# key is created here, on your machine, from the system's cryptographic random source. .env is
# git-ignored. Re-running is safe - existing values are kept, only missing ones are added - so rotating
# one secret is: delete its line, run this script, restart the affected containers.
#
#   scripts/gen-env.sh              create or top up .env
#   scripts/gen-env.sh --force      regenerate every secret (invalidates running stacks and volumes!)
#
# Works in Git Bash / WSL / Linux / macOS (needs bash and openssl).
set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE=".env"
FORCE=false
[ "${1:-}" = "--force" ] && FORCE=true

command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }

secret() { openssl rand -base64 48 | tr -d '/+=\n' | cut -c1-"${1:-32}"; }

touch "$ENV_FILE"
chmod 600 "$ENV_FILE" 2>/dev/null || true

if $FORCE; then : > "$ENV_FILE"; fi

added=0
ensure() { # KEY VALUE
  if ! grep -q "^$1=" "$ENV_FILE"; then
    printf '%s=%s\n' "$1" "$2" >> "$ENV_FILE"
    added=$((added + 1))
  fi
}

if [ ! -s "$ENV_FILE" ]; then
  cat >> "$ENV_FILE" <<'EOF'
# Generated by scripts/gen-env.sh - do not commit, do not share.
EOF
fi

# --- datastores ---------------------------------------------------------------------------------
ensure POSTGRES_ADMIN_PASSWORD   "$(secret)"
for svc in CUSTOMER ORDER INVENTORY PAYMENT NOTIFICATION; do
  ensure "${svc}_DB_PASSWORD"    "$(secret)"
done
ensure REDIS_PASSWORD            "$(secret)"
ensure VAULT_DB_ADMIN_PASSWORD   "$(secret)"

# --- identity provider (Keycloak) ---------------------------------------------------------------
ensure KC_BOOTSTRAP_ADMIN_USERNAME admin
ensure KC_BOOTSTRAP_ADMIN_PASSWORD "$(secret)"
ensure NOTIFICATION_CLIENT_SECRET  "$(secret 40)"

# Development-only identities used by scripts and the Karate suite (see infrastructure/keycloak/seed-dev.sh).
ensure E2E_CLIENT_SECRET         "$(secret 40)"
ensure E2E_ADMIN_PASSWORD        "$(secret)"
ensure E2E_MANAGER_PASSWORD      "$(secret)"
ensure E2E_USER_PASSWORD         "$(secret)"

# --- platform services & dashboards -------------------------------------------------------------
ensure GRAFANA_ADMIN_PASSWORD    "$(secret)"
ensure EUREKA_PASSWORD           "$(secret)"
ensure CONFIG_SERVER_PASSWORD    "$(secret)"

# --- PKI (smallstep step-ca), used by docker-compose.pki.yml -------------------------------------
ensure STEP_CA_PASSWORD          "$(secret 40)"

# --- Vault, used by docker-compose.vault.yml ------------------------------------------------------
# The root token and unseal key are created by vault-init and stored under .vault/ (also git-ignored);
# nothing static is needed here.

echo "$ENV_FILE: $added new secret(s) generated."
echo "Start the stack with:  docker compose up -d --build"
