-- Payment Service - H2 Sample Data

INSERT INTO payments (id, order_id, amount, status, created_at, updated_at)
VALUES
    (1, 1, 299.99, 'PROCESSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 2, 99.99, 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 3, 149.97, 'PROCESSING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 4, 199.99, 'PROCESSING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 5, 199.98, 'PROCESSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE
    order_id = VALUES(order_id),
    amount = VALUES(amount),
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP;
